name: QMOI Production Smoke CI

on:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install minimal deps
      run: |
        python -m pip install --upgrade pip
        pip install -r qmoi-enhanced/qmoi-enhanced/scripts/requirements-secrets.txt || true
    - name: Run smoke checks
      run: |
        python -m py_compile qmoi-enhanced/qmoi-enhanced/qmoi_orchestrator.py || true
        python -m py_compile qmoi-enhanced/qmoi-enhanced/qmoi_build_all.py || true
    - name: Upload artifact list
      run: |
        ls -la .qmoi || true
