name: QMOI Secrets Demo

on:
  workflow_dispatch:

jobs:
  decrypt-demo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install deps
      run: python -m pip install cryptography

    - name: Decrypt github token (demo)
      env:
        QMOI_MASTER_KEY: ${{ secrets.QMOI_MASTER_KEY }}
      run: |
        python - <<'PY'
        from scripts.qmoi_secret_manager import decrypt_secret_file
        v = decrypt_secret_file('.qmoi/github_token.enc')
        if v:
            print('Encrypted token present and decryptable (length):', len(v))
        else:
            print('No decrypted token available; ensure .qmoi/github_token.enc exists and QMOI_MASTER_KEY is set')
        PY
